  /* -*- tab-width: 2; mode: c; -*-
  *
  * A program for the nRF52840 to transmit ASTM F3411/ASD-STAN 4709-002/opendroneid 
  * remote identification signals over Bluetooth.
  * 
  * Copyright (c) 2023 Steve Jack
  *
  * Apache 2.0 licence
  *
  * Parts of this program are taken from samples which are
  * Copyright (c) Intel Corporation 
  * or
  * Copyright (c) Nordic Semiconductor
  *
  */

  #pragma GCC diagnostic warning "-Wunused-variable"
  #pragma GCC diagnostic ignored "-Wparentheses"
  // #pragma GCC diagnostic ignored "-Wunused-but-set-variable"

  #include "remote_id.h"

  #include <zephyr/logging/log.h>
  #include <zephyr/sys/printk.h>

  #include <zephyr/drivers/uart.h>
  #include <zephyr/drivers/gpio.h>

  #include <zephyr/bluetooth/bluetooth.h>
  #include <zephyr/bluetooth/hci.h>

  // #include <zephyr/random/rand32.h>

  #include "gps2.h"
  #include "odid_bt.h"
  #if SPEKTRUM
  #include "spektrum_i2c.h"
  #endif

  #include <psa/crypto.h>

  //

  static const char                 uav_operator[] = UAV_OPERATOR,
                                    self_id[]      = SELF_ID,
                                  *program_name   = "Remote ID";
  static char                       uav_id[25]     = UAV_ID;
  static const ODID_uatype_t        ua_type        = UA_TYPE;
  static const ODID_category_EU_t   category       = EU_CATEGORY;

  //

  static GPS2                       gps;
  static RID_open                   squitter;
  #if SPEKTRUM
  static Spektrum_I2C               spektrum;
  #endif

  static ODID_UAS_Data              UAS_data;
  const uint64_t                    odid_datum     = 1546300800;

  static const struct device       *usb_ser_dev    = NULL,
                                  *uart_dev       = DEVICE_DT_GET(DT_NODELABEL(uart0));
  #if defined(CONFIG_BOARD_NRF52840DONGLE_NRF52840)
  const char                        config_board[] = "nrf52840 dongle";
  static const struct gpio_dt_spec  led_green      = GPIO_DT_SPEC_GET(DT_ALIAS(led0_green),gpios);
  static const struct gpio_dt_spec  led_red        = GPIO_DT_SPEC_GET(DT_ALIAS(led1_red),gpios);
  static const struct gpio_dt_spec  led_green1     = GPIO_DT_SPEC_GET(DT_ALIAS(led1_green),gpios);
  static const struct gpio_dt_spec  led_blue       = GPIO_DT_SPEC_GET(DT_ALIAS(led1_blue),gpios);
  #else
  const char                        config_board[] = "nrf52";
  static const struct gpio_dt_spec  led_red        = GPIO_DT_SPEC_GET(DT_ALIAS(led0),gpios);
  static const struct gpio_dt_spec  led_green      = GPIO_DT_SPEC_GET(DT_ALIAS(led1),gpios);
  static const struct gpio_dt_spec  led_blue       = GPIO_DT_SPEC_GET(DT_ALIAS(led2),gpios);
  #endif

  #if 0
  static int                        time_set = 0;
  #endif
  static int                        base_set = 0, build_report = 0;

  static void init_odid(const char *,char *,const char *);
  static void status_leds(uint32_t,uint32_t,int,int);

  // NOTE: the drone's Ed25519 private key is intentionally NOT stored here anymore. The Link is
  // now a pre-signed HDA endorsement, so the drone signs nothing and needs no private key. When
  // the Manifest (telemetry authentication) is added, the key MUST live in secure storage
  // (nRF52840 KMU / CryptoCell), never as a plaintext constant in this source.

  // DET of the parent HDA (from drip_provision.py; matches the HDA key published in DNS)
  static const uint8_t auth_hda_det[16] = {
      0x20, 0x01, 0x00, 0x30, 0x3f, 0xf8, 0x04, 0x02,
      0xb8, 0x39, 0xe5, 0x33, 0xdb, 0x24, 0x3e, 0xf3
  };

  // DET of the drone (RFC 9374 Context ID cSHAKE; regenerated by drip_provision.py)
  static const uint8_t drone_det[16] = {
      0x20, 0x01, 0x00, 0x30, 0x3f, 0xf8, 0x04, 0x02,
      0xa4, 0x6f, 0xb5, 0x09, 0xaf, 0xce, 0x2c, 0xb0
  };

  // HDA-endorsed DRIP Link (RFC 9575), generated by drip_provision.py and signed by the HDA
  // key - NOT by the drone. The drone only broadcasts this pre-signed blob, so it no longer
  // signs on-device for the Link. message = VNB|VNA|childDET|childHI|parentDET (72 bytes).
  static const uint8_t endorsement_message[72] = {
      0x8e, 0x5f, 0x2d, 0x0e, 0x9e, 0x70, 0xf9, 0x20, 0x20, 0x01, 0x00, 0x30, 0x3f, 0xf8, 0x04, 0x02,
      0xa4, 0x6f, 0xb5, 0x09, 0xaf, 0xce, 0x2c, 0xb0, 0xf5, 0x05, 0x70, 0x4e, 0xb5, 0x44, 0xf8, 0x61,
      0x19, 0x0f, 0x2d, 0x8e, 0xda, 0xc9, 0xba, 0x83, 0xf3, 0x20, 0xd5, 0xe3, 0x87, 0x26, 0xb3, 0xf5,
      0x1c, 0x22, 0x08, 0x51, 0x32, 0x0e, 0xc7, 0xe6, 0x20, 0x01, 0x00, 0x30, 0x3f, 0xf8, 0x04, 0x02,
      0xb8, 0x39, 0xe5, 0x33, 0xdb, 0x24, 0x3e, 0xf3
  };
  static const uint8_t endorsement_signature[64] = {
      0x71, 0xd4, 0x34, 0x2b, 0x50, 0xea, 0xc9, 0xb6, 0x2a, 0x32, 0xbb, 0x62, 0xa3, 0x83, 0xc4, 0xc6,
      0x57, 0x7e, 0xcd, 0xef, 0xe6, 0x9e, 0xe9, 0x87, 0x7a, 0x85, 0x4d, 0x29, 0x77, 0x23, 0x48, 0x76,
      0x1c, 0x2b, 0x80, 0xeb, 0x15, 0x75, 0x13, 0x90, 0xb0, 0xbf, 0xe5, 0x65, 0x3f, 0xc0, 0xc1, 0xb8,
      0x90, 0xac, 0x3a, 0x86, 0x56, 0x26, 0x95, 0x59, 0x95, 0xfc, 0xbd, 0x82, 0x84, 0x20, 0x67, 0x00
  };

  static void build_auth_link_message(ODID_UAS_Data *uas) {

      // Page-0 timestamp = the endorsement's VNB (first 4 bytes, little-endian).
      uint32_t vnb = endorsement_message[0] | (endorsement_message[1] << 8)
                   | (endorsement_message[2] << 16) | ((uint32_t)endorsement_message[3] << 24);

      // Complete payload : SAM type(1) | message(72) | signature(64) = 137 bytes
      uint8_t auth_payload[137];
      auth_payload[0] = 0x01; // SAM type = Link
      memcpy(auth_payload + 1,  endorsement_message,   72);
      memcpy(auth_payload + 73, endorsement_signature, 64);

      // Page 0 : 17 bytes of data
      uas->Auth[0].AuthType      = ODID_AUTH_SPECIFIC_AUTHENTICATION;
      uas->Auth[0].DataPage      = 0;
      uas->Auth[0].LastPageIndex = 6;
      uas->Auth[0].Length        = 137;
      uas->Auth[0].Timestamp     = vnb;
      memcpy(uas->Auth[0].AuthData, auth_payload, 17);

      // Pages 1 to 6 : 23 bytes each
      for (int page = 1; page <= 6; page++) {
          int offset    = 17 + (page - 1) * 23;
          int to_copy   = (int)sizeof(auth_payload) - offset;
          if (to_copy <= 0) break;
          if (to_copy > 23) to_copy = 23;

          uas->Auth[page].AuthType = ODID_AUTH_SPECIFIC_AUTHENTICATION;
          uas->Auth[page].DataPage = page;
          memcpy(uas->Auth[page].AuthData, auth_payload + offset, to_copy);
      }
  }

  /*
  *
  */

  int main(void) {
  struct bt_le_ext_adv_info ext_adv_info;

  // init data
  init_odid(uav_operator, uav_id, self_id);

  // bluetooth init
  squitter.begin(&led_blue, uav_operator, &UAS_data, &ext_adv_info);

  printk("\n*** EMULATEUR REMOTE ID PRET ***\n");
  printk("Programme: %s\n", program_name);
  printk("Statut: Emission en cours...\n");
  
  build_auth_link_message(&UAS_data);

  // loop
  while (1) {

    squitter.foreground(&UAS_data);

    k_sleep(K_MSEC(200));

    // blinking led
    status_leds(k_uptime_get_32(), k_uptime_get_32(), 10, 1);
  }

  return 0;
}
  /*
  *
  */

  void txt_message(const char *text) {
    printk("[MSG] %s\n", text);
  }

  void txt_message(const char *text, const int message, const int messages, const int severity) {
    printk("[MSG] %s\n", text);
  }

  /*
  *
  */

  void debug_message(const char *message) {
    if (!usb_ser_dev) return;

    while (*message) {
      uart_poll_out(usb_ser_dev,*message++);
    }
    
    return;
  }

  /*
  *
  */

  static void init_odid(const char *uav_op,char *uav,const char *self) {

    uint32_t            sn1, sn2;
    ODID_Location_data *location;
    ODID_System_data   *system;

    memset(&UAS_data,0,sizeof(UAS_data));

    location = &UAS_data.Location;
    system   = &UAS_data.System;

    //

    //if (uav[0] == '~') {

    //  sn1 = sys_rand32_get() % 1000000;
    //  sn2 = sys_rand32_get() % 1000000;

    //  sprintf(uav,"ZZZZL%06u%06u",sn1,sn2);
    //}

    //

    UAS_data.BasicID[0].UAType =
    UAS_data.BasicID[1].UAType = ua_type;

  // --- DET IPV6 injection ---
  static const unsigned char ipv6_det[] = {
      0x20, 0x01, 0x00, 0x30, 0x3f, 0xf8, 0x04, 0x02,
      0xa4, 0x6f, 0xb5, 0x09, 0xaf, 0xce, 0x2c, 0xb0,
      0x00, 0x00, 0x00, 0x00
  };

  UAS_data.BasicID[0].IDType = ODID_IDTYPE_SPECIFIC_SESSION_ID;
  memcpy(UAS_data.BasicID[0].UASID, ipv6_det, sizeof(ipv6_det));

  UAS_data.BasicID[1].IDType = ODID_IDTYPE_SPECIFIC_SESSION_ID;
  memcpy(UAS_data.BasicID[1].UASID, ipv6_det, sizeof(ipv6_det));
  // --- FIN INJECTION ---
  printk("\n=== DEMARRAGE DU DRONE ===\n");
  printk("DET (IPv6) injecté avec succes !\n");
  printk("==========================\n");

    // --- DRONE'S COORDINATES ---
    location->Status         = ODID_STATUS_AIRBORNE; 
    location->Latitude       = 48.6248;              
    location->Longitude      = 2.4449;               
    location->AltitudeGeo    = 150.0;                
    location->AltitudeBaro   = 150.0;                
    location->Height         = 50.0;                 
    location->Direction      = 180.0;                
    location->SpeedHorizontal = 10.5;                
    location->SpeedVertical   = 1.0;                 
    
    location->HorizAccuracy  = ODID_HOR_ACC_10_METER;
    location->VertAccuracy   = ODID_VER_ACC_10_METER;
    location->BaroAccuracy   = ODID_VER_ACC_10_METER;
    location->SpeedAccuracy  = ODID_SPEED_ACC_10_METERS_PER_SECOND;
    location->TSAccuracy     = ODID_TIME_ACC_0_1_SECOND;
    location->TimeStamp      = 30.0;                

    location->HeightType         = ODID_HEIGHT_REF_OVER_TAKEOFF;

  // --- OPERATOR's COORDINATES ---
    system->OperatorLocationType = ODID_OPERATOR_LOCATION_TYPE_TAKEOFF;
    system->OperatorLatitude     = 48.6251;          
    system->OperatorLongitude    = 2.4422;
    system->OperatorAltitudeGeo  = 35.0;          
    system->AreaCount            = 1;
    system->AreaRadius           = 0;                
    system->ClassificationType   = ODID_CLASSIFICATION_TYPE_EU;
    system->CategoryEU           = ODID_CATEGORY_EU_OPEN;
    system->ClassEU              = ODID_CLASS_EU_CLASS_1;

    system->AreaCeiling          =
    system->AreaFloor            = -1000.0;

  #if ! (ID_USA || ID_JAPAN)
    if (category) {
      system->ClassificationType = ODID_CLASSIFICATION_TYPE_EU;
      system->CategoryEU         = category;
      system->ClassEU            = ODID_CLASS_EU_UNDECLARED;
    }
  #endif

  // --- OPERATOR ID ---
  // The Operator ID is the operator's registration number (issued by the CAA), NOT the DET.
  // The DET is the UAS/aircraft identity (BasicID); the operator identity is separate.
  UAS_data.OperatorID.OperatorIdType = ODID_OPERATOR_ID;
  strncpy(UAS_data.OperatorID.OperatorId, uav_op, ODID_ID_SIZE);

  // --- SELF ID ---
  UAS_data.SelfID.DescType   = ODID_DESC_TYPE_TEXT;
  strncpy(UAS_data.SelfID.Desc, "DRIP CASSIOPEE", ODID_STR_SIZE);

    // Build and sign the authentication message (SAM Link) to be included in the broadcasted data
    build_auth_link_message(&UAS_data);

    return;
  }

  /*
  *
  */

  // #define STATUS_LED DT_N_ALIAS_statusled
  
  void status_leds(uint32_t uptime,uint32_t last_gps,int sats,int fix) {

    static int                 phase = -1;
    static uint32_t            last_update = 0;
  #if defined(STATUS_LED)
    static struct gpio_dt_spec external_led = GPIO_DT_SPEC_GET(DT_ALIAS(statusled),gpios);
  #endif

    if (phase < 0) {

      gpio_pin_configure_dt(&led_green,GPIO_OUTPUT_ACTIVE);
      gpio_pin_set_dt(&led_green,0);
  #if defined(STATUS_LED)
      gpio_pin_configure_dt(&external_led,GPIO_OUTPUT_ACTIVE);
      gpio_pin_set_dt(&external_led,0);
  #endif
      phase = 0;
    }

    if ((uptime - last_update) < 100) {
      return;
    }

    last_update = uptime;

    switch (phase) {

    case 0:
      if ((uptime - last_gps) < 2000) {
        gpio_pin_set_dt(&led_green,1);
  #if defined(STATUS_LED)
        gpio_pin_set_dt(&external_led,1);
  #endif
      }
      break;

    case  6:
    case  8:
    case 10:
    case 12:
    case 14:
      gpio_pin_set_dt(&led_green,0);
  #if defined(STATUS_LED)
        gpio_pin_set_dt(&external_led,0);
  #endif
      break;

    case  9:
      if (sats > 3) {
        gpio_pin_set_dt(&led_green,1);
  #if defined(STATUS_LED)
        gpio_pin_set_dt(&external_led,1);
  #endif
      }
      break;

    case 11:
      if (sats > 9) {
        gpio_pin_set_dt(&led_green,1);
  #if defined(DT_N_ALIAS_statusled)
        gpio_pin_set_dt(&external_led,1);
  #endif
      }
      break;
    }

    if (++phase > 19) {
      phase = 0;
    }

    return;
  }